name: falavastr
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0" 

dependencies:
  scoped_model: ^1.0.1
  shared_preferences: ^0.4.3
  intl: ^0.15.7
  date_utils: ^0.1.0+2
  draggable_scrollbar: ^0.0.4
  rxdart: ^0.20.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Grebnev
      fonts:
        - asset: lib/fonts/GREBNEVUCS.TTF 
    - family: Balkara
      fonts:
        - asset: lib/fonts/Balkara.ttf
    - family: OpenSans
      fonts:
        - asset: lib/fonts/OpenSans-Regular.ttf
        - asset: lib/fonts/OpenSans-Bold.ttf
        - asset: lib/fonts/OpenSans-Italic.ttf
        - asset: lib/fonts/OpenSans-Light.ttf
    - family: Orthodox
      fonts:
        - asset: lib/fonts/OrtUCS8.ttf
    - family: Turaevo
      fonts:
        - asset: lib/fonts/Turaevo.ttf

  assets:
    - lib/calendar/json/minea/yanvar.json
    - lib/calendar/json/minea/fevral.json
    - lib/calendar/json/minea/mart.json
    - lib/calendar/json/minea/aprel.json
    - lib/calendar/json/minea/maii.json
    - lib/calendar/json/minea/juni.json
    - lib/calendar/json/minea/july.json
    - lib/calendar/json/minea/avgust.json
    - lib/calendar/json/minea/september.json
    - lib/calendar/json/minea/october.json
    - lib/calendar/json/minea/november.json
    - lib/calendar/json/minea/december.json
    - lib/calendar/json/svyatcy/svyatcy.json
    - lib/calendar/json/oktay/oktay.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
